apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3tier-node-app-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: "default"
  source:
    repoURL: 'https://github.com/bogdansucila/gitops-demo.git'
    path: 'helm/3tier-node-app'
    helm:
      parameters:
        - name: env_variables.api.db_name
          value: "api"
        - name: env_variables.api.db_host
          value: "staging-toptal-project-rds.cci7bfyhjfmq.eu-west-1.rds.amazonaws.com"
        - name: images.api.version
          value: "latest"
        - name: images.web.version
          value: "latest"
        - name: ingress.certificate_arn
          value: "arn:aws:acm:eu-west-1:110932912312:certificate/5d4bf59b-b393-429b-9bc0-181c328652ef"
        - name: ingress.fqdn
          value: "bogdan-dev-project.tk"
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true