apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3tier-node-app-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: "default"
  source:
    repoURL: 'https://github.com/bogdansucila/gitops-demo.git'
    path: 'helm/3tier-node-app'
    helm:
      parameters:
        - name: env_variables.api.db_name
          value: "api"
        - name: env_variables.api.db_host
          value: "production-toptal-project-rds.cci7bfyhjfmq.eu-west-1.rds.amazonaws.com"
        - name: images.api.version
          value: "latest"
        - name: images.web.version
          value: "v2"
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

      