---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toptal-project-api
  labels:
    app: toptal-project-api
spec:
  selector:
    matchLabels:
      app: toptal-project-api
  template:
    metadata:
      labels:
        app: toptal-project-api
    spec:
      serviceAccountName: {{ .Release.Namespace }}-toptal-project-api
      containers:
      - name: api
        image: "{{ .Values.images.api.repository }}/toptal-project-api:{{ .Values.images.api.version }}"
        imagePullPolicy: {{ .Values.images.api.pullPolicy }}
        securityContext:
          privileged: false
          runAsUser: 65534
        resources:
          limits:
            cpu: {{ .Values.resources.api.limits.cpu }}
            memory:  {{ .Values.resources.api.limits.memory }}
          requests:
            cpu:  {{ .Values.resources.api.requests.cpu }}
            memory:  {{ .Values.resources.api.requests.memory }}
        env:
        - name: PORT
          value: "8081"
        - name: DB
          value: {{ .Values.env_variables.api.db_name }}
        - name: DBHOST
          value: {{ .Values.env_variables.api.db_host }}
        - name: DBPORT
          value: "5432"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Namespace }}-toptal-project-rds-secrets
              key: DBUSER
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Namespace }}-toptal-project-rds-secrets
              key: DBPASS
      {{- with .Values.tolerations }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}