---
apiVersion: v1
kind: Service
metadata:
  name: toptal-project-api
spec:
    selector:
      app: toptal-project-api
    ports:
    - name: api-8081
      protocol: TCP
      port: 8081
      targetPort: {{ .Values.env_variables.api.port }}
    type: NodePort
