---
apiVersion: v1
kind: Service
metadata:
  name: toptal-project-web
spec:
    selector:
      app: toptal-project-web
    ports:
    - name: web-8080
      protocol: TCP
      port: 8080
      targetPort: {{ .Values.env_variables.web.port }}
    type: NodePort
