apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: albingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: "default"
  source:
    repoURL: 'https://aws.github.io/eks-charts'
    targetRevision: 1.4.0
    chart: aws-load-balancer-controller
    helm:
      values: |
        clusterName: toptal-project
        serviceAccount:
          annotations: 
            eks.amazonaws.com/role-arn: arn:aws:iam::110932912312:role/ALBIngressRole
          name: aws-load-balancer-controller
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true