apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: albingress-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: "default"
  source:
    repoURL: 'https://github.com/aws/eks-charts.git'
    path: 'stable/aws-load-balancer-controller/crds'
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true